### ISSUE TITLE
README Has Not Been Updated From Skeleton

### ISSUE THREAD

**Issue by mcdonnnj** [cisagov/action-apb-dashboard#1]
# 🐛 Bug Report

The README for this project has not been updated from the skeleton. It provides no useful information about what this project is or how it is intended to be used.

## To Reproduce

Look at the README.

## Expected behavior

Some explanation about the project and how it is used.

**Comment by jsf9k** [comment]
Good catch.  @felddy, can you take care of this?

**Comment by mcdonnnj** [comment]
https://github.com/cisagov/action-apb-dashboard/pull/4 took care of this.
